version: '3.1'

services:
  mongo:
    image: mongo
    container_name: sas-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - '/c/personal/facultate/sac/volumes/mongo/data:/data/db'

  mongo-express:
    image: mongo-express
    container_name: sas-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  rabbitmq:
    container_name: sas-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /c/personal/facultate/sac/volumes/rabbit/data/:/var/lib/rabbitmq
        - /c/personal/facultate/sac/volumes/rabbit/log/:/var/log/rabbitmq
        - ./backend/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        - ./backend/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  proxy:
    image: nginx
    container_name: sas-proxy
    volumes:
      - ./backend/proxy:/etc/nginx/templates
    ports:
      - "8800:80"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX.conf
      - IDENTITY_URI=http://identity:8801
      - RECOMMENDATION_URI=http://recommendation:8802

  identity:
    container_name: sas-identity
    build: ./backend/identity
    restart: always
    ports:
      - 8801:8801
    environment:
      CONNECTION_STRING: mongodb://root:example@mongo:27017/
      SECRET: SASProject

  recommendation:
    container_name: sas-recommendation
    build: ./backend/recommendation
    restart: always
    ports:
      - 8802:8802
    environment:
      CONNECTION_STRING: mongodb://root:example@mongo:27017/
      IDENTITY_URI: http://identity:8801
      SECRET: SASProject
      RABBITMQ_SERVER: rabbitmq

  scraping:
    container_name: sas-scraping
    build: ./backend/scraping
    restart: always
    environment:
      RABBITMQ_SERVER: rabbitmq
      CONNECTION_STRING: mongodb://root:example@mongo:27017/

  frontend:
    container_name: sas-frontend
    build: ./frontend
    restart: always
    ports:
      - 4200:4200
